### ISSUE TITLE
Error 404 on http://localhost:3000/admin

### ISSUE THREAD

**Issue by mykhaliuk** [suevalov/next-blog-firestore#2]
After all steps described in readme get error 404 before page starts loading on attempt to go to /admin page.

**Comment by suevalov** [comment]
I experienced this issue as well. I believe it's connected to https://github.com/zeit/next.js/issues/2833, but I didn't have time to fix that. Would be glad if you solve the problem and make PR :)

**Comment by johndevor** [comment]
Not sure if this helps, but I found that disabling this line stopped the 404 from happening:

`const firebase = require("@firebase/app").default;`

(in firebaseInit.js)

Any ideas on why this might be the case?

**Comment by johndevor** [comment]
Don't know what happened here but it seems to have magically resolved. Just did a fresh setup of the project and no 404 page on /admin now.
