### ISSUE TITLE
Could you tell me how to create category?

### ISSUE THREAD

**Issue by HibinoTomohiro22** [suevalov/next-blog-firestore#3]
Thank you for making this.
I can open /admin.
But, I can't post new articles because I can't create category.
How could I create blog category??

**Comment by nhidonghocphat** [comment]
@HibinoTomohiro22  you can edit in file /utils/config.js to change menu
and go to firebase database to change categories

> Thank you for making this.
> I can open /admin.
> But, I can't post new articles because I can't create category.
> How could I create blog category??

**Comment by HibinoTomohiro22** [comment]
@nhidonghocphat Thank you!
